cf:
  apiHost: api.run.pcfone.io
  passcode: xxxxxx

token:
  provider: sso

spring:
  profiles.include: jdbc

logging:
  level:
    de.flapdoodle.embed.mongo: INFO
    org.springframework: INFO
    com.sendgrid: DEBUG
    org.cloudfoundry.reactor: DEBUG

# Set schedule for this task to adhere to
# @see https://crontab.guru for help, first parameter is seconds
cron:
  collection: "0 0 0 * * *" 
  execution: "0 0 2 * * *"

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,logfile

---
spring:
  profiles: jdbc

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration

  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:cf-butler
    username: sa
    password: 
